name: graphics-core22-samples
adopt-info: samples
grade: stable
summary: sample apps to check and test graphics-core22
description: sample apps to check and test graphics-core22 plug
confinement: strict
base: core22

architectures:
  - build-on: amd64

environment:
  XDG_CACHE_HOME:  $SNAP_USER_COMMON/.cache
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config

layout:
  /usr/share/drirc.d:  # Used by mesa-core22 for app specific workarounds
    bind: $SNAP/graphics/drirc.d
  /usr/share/X11/XErrorDB:
    bind: $SNAP/graphics/usr/share/X11/XErrorDB
  /usr/share/X11/locale:
    bind: $SNAP/graphics/usr/share/X11/locale

plugs:
  wayland:
  opengl:
  network-bind:
  kernel-module-observe:
  hardware-observe:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: nvidia-core22

apps:
  bandwidthTest:
    command-chain: [bin/graphics-core22-wrapper]
    command: usr/bin/bandwidthTest

  deviceQuery:
    command-chain: [bin/graphics-core22-wrapper]
    command: usr/bin/deviceQuery

  glxinfo:
    command-chain: [bin/graphics-core22-wrapper]
    command: usr/bin/glxinfo

  eglinfo:
    command-chain: [bin/graphics-core22-wrapper]
    command: usr/bin/eglinfo

  es2info:
    command-chain: [bin/graphics-core22-wrapper]
    command: usr/bin/es2_info

parts:
  samples:
    source: https://github.com/NVIDIA/cuda-samples
    source-tag: v11.5
    source-type: git
    source-depth: 1
    plugin: nil
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags)"
    build-packages:
      - build-essential
      - libnvidia-compute-515-server
      - nvidia-cuda-toolkit
    stage-packages:
      - mesa-utils
      - mesa-utils-extra
    override-build: |
      make -C Samples/bandwidthTest CUDA_PATH=/usr/lib/nvidia-cuda-toolkit
      make -C Samples/deviceQuery CUDA_PATH=/usr/lib/nvidia-cuda-toolkit
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin/
      cp bin/x86_64/linux/release/* $SNAPCRAFT_PART_INSTALL/usr/bin/
    stage:
      - usr/bin/bandwidthTest
      - usr/bin/deviceQuery
      - usr/bin/glxinfo*
      - usr/bin/eglinfo*
      - usr/bin/es2_info*

  graphics-core22:
    source: https://github.com/MirServer/graphics-core22.git
    plugin: dump
    prime:
      - bin/graphics-core22-wrapper
